In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [6]:
s = np.array(5)
print(s)
print("=============")
v = np.array([1,2,3,4])
print(v)
print("=============")
m = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(m)
 

5
[1 2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
s = np.array(5)
print(s.ndim)
print(s.shape)
print("=============")
v = np.array([1,2,3,4])
print(v.ndim)
print(v.shape)
print("=============")
m = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(m.ndim)
print(m.shape)
 

0
()
1
(4,)
2
(3, 3)


In [12]:
vec =np.array([1,2,3,4,5,6])
mat = vec.reshape(3,2)
mat.shape[0]

3

In [15]:
vec =np.array([1,2,3,4])
mat=vec.reshape(vec.shape[0],1)
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [18]:
def array_reshape(arr, rows, cols):
    try:
        arr = np.array(arr)
        return arr.reshape(rows, cols)
    except (TypeError, ValueError) as e:
        raise ValueError(f"invalid reshape operation:(e)")

In [19]:
vec = [1,2,3,4,5,6]
array_reshape(vec, 2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
#object -->string -->float -->int -->bool
mat = np.array([[1,2,3],
                [4,5.5,6],
                [7,8,9]])
print(mat.dtype)

float64
